# Generated by Django 2.1.5 on 2021-06-30 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 12, 45, 59, 812497), verbose_name='date published'),
        ),
    ]
